### PR TITLE
VS2022 Build

### PR DESCRIPTION
**Pull request by ogamespec**
For fans of Visual Studio. I made a separate folder so that there is no conflict.

In cpu.cpp I added special processing to support multiplication intrinsics.

~~TBD: I was unable to mate the PortAudio nuget package with the build.~~ Fixed.

### CODE REVIEW

**Comment by nadiaholmquist** [comment]
Adding an IDE-specific build system seems maybe a bit out of scope to me for a project that aims to be quite cross-platform and already builds fine with MinGW Windows.

Maybe if/when the project becomes more mature it would be better to try and make the existing Make-based build system more portable? That's something it could probably need eventually.

**Comment by ogamespec** [comment]
I feel more comfortable in a Visual Studio environment than in a console with MinGW and half of linux.

**Comment by Hydr8gon** [comment]
I admit that this isn't something I would merge to the main branch, mainly because I wouldn't be able to maintain it. I also had issues in the past when I supported Visual Studio for NooDS, such as the build being slower than one made with GCC, and the VS compiler erroring on things that were fine with GCC. I'm happy to keep the PR open though, so Visual Studio users that want it can find it.

**Comment by ogamespec** [comment]
@Hydr8gon 
Let me make a simpler PR with the VS2022 folder in .gitignore :)

**Comment by ogamespec** [comment]
I think that would be better. I hope you don't mind the `_MSC_VER` macro and the bits of code associated with it? :)

**Comment by Hydr8gon** [comment]
Eh I guess that's fine, I plan to eventually make that multiplication code portable anyway.

**Pull request merged**
